language: python
python:
  - "3.6"     
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools

install:
  - pip install -r requeriments.txt
  - pip install .

script:
  - pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)